export const SET_FILTER_SEARCH_VALUE = 'SET_FILTER_SEARCH_VALUE';
export const SET_FILTER_SORT_TYPE = 'SET_FILTER_SORT_TYPE';
export const SET_FILTER_ITEMS = 'SET_FILTER_ITEMS';
export const SET_FILTER_ITEMS_CURRENT_PAGE = 'SET_FILTER_ITEMS_CURRENT_PAGE';
